{{- if and .Values.central.enabled .Values.central.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argus.fullname" . }}-frontend
  labels:
    {{- include "argus.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "argus.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: {{ include "argus.image" (dict "registry" .Values.global.imageRegistry "repository" .Values.central.frontend.image.repository "tag" .Values.global.imageTag) }}
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          ports:
            - containerPort: {{ .Values.central.frontend.service.port }}
              name: http
          resources:
            {{- toYaml .Values.central.frontend.resources | nindent 12 }}
{{- end }}
