{{- if .Values.central.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "argus.fullname" . }}-backend
  labels:
    {{- include "argus.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.central.backend.service.port }}
      targetPort: http
{{- end }}
