server_name: argus-edge-leaf

jetstream {
  store_dir: /data/jetstream
}

http: 0.0.0.0:8222
listen: 0.0.0.0:4222

authorization {
  default_permissions: {
    publish: {
      allow: [
        "evt.edge.tracking.*",
        "evt.rule.*",
        "incident.triggered.*",
        "edge.heartbeat.*",
        "support.tunnel.*",
        "_INBOX.>"
      ]
    }
    subscribe: {
      allow: [
        "cmd.camera.*",
        "_INBOX.>"
      ]
    }
  }
}

leafnodes {
  remotes = [
    {
      urls: ["nats://host.docker.internal:7422"]
    }
  ]
}
