/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthcheck */
        get: operations["healthcheck_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/debug/protected": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Debug Protected */
        get: operations["debug_protected_api_v1_debug_protected_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/edge/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Edge Ping */
        post: operations["edge_ping_api_v1_edge_ping_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sites */
        get: operations["list_sites_api_v1_sites_get"];
        put?: never;
        /** Create Site */
        post: operations["create_site_api_v1_sites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Site */
        get: operations["get_site_api_v1_sites__site_id__get"];
        put?: never;
        post?: never;
        /** Delete Site */
        delete: operations["delete_site_api_v1_sites__site_id__delete"];
        options?: never;
        head?: never;
        /** Update Site */
        patch: operations["update_site_api_v1_sites__site_id__patch"];
        trace?: never;
    };
    "/api/v1/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cameras */
        get: operations["list_cameras_api_v1_cameras_get"];
        put?: never;
        /** Create Camera */
        post: operations["create_camera_api_v1_cameras_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cameras/source-probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Probe Camera Source */
        post: operations["probe_camera_source_api_v1_cameras_source_probe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cameras/{camera_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Camera */
        get: operations["get_camera_api_v1_cameras__camera_id__get"];
        put?: never;
        post?: never;
        /** Delete Camera */
        delete: operations["delete_camera_api_v1_cameras__camera_id__delete"];
        options?: never;
        head?: never;
        /** Update Camera */
        patch: operations["update_camera_api_v1_cameras__camera_id__patch"];
        trace?: never;
    };
    "/api/v1/cameras/{camera_id}/worker-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Camera Worker Config */
        get: operations["get_camera_worker_config_api_v1_cameras__camera_id__worker_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cameras/{camera_id}/setup-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Camera Setup Preview */
        get: operations["get_camera_setup_preview_api_v1_cameras__camera_id__setup_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cameras/{camera_id}/setup-preview/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Camera Setup Preview Image */
        get: operations["get_camera_setup_preview_image_api_v1_cameras__camera_id__setup_preview_image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_api_v1_models_get"];
        put?: never;
        /** Create Model */
        post: operations["create_model_api_v1_models_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Model */
        patch: operations["update_model_api_v1_models__model_id__patch"];
        trace?: never;
    };
    "/api/v1/model-catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Model Catalog */
        get: operations["list_model_catalog_api_v1_model_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/edge/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Edge Node */
        post: operations["register_edge_node_api_v1_edge_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/edge/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Edge Telemetry */
        post: operations["ingest_edge_telemetry_api_v1_edge_telemetry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/edge/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Edge Heartbeat */
        post: operations["edge_heartbeat_api_v1_edge_heartbeat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/fleet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Fleet Overview */
        get: operations["get_fleet_overview_api_v1_operations_fleet_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Bootstrap Material */
        post: operations["create_bootstrap_material_api_v1_operations_bootstrap_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History */
        get: operations["get_history_api_v1_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History Series */
        get: operations["get_history_series_api_v1_history_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History Classes */
        get: operations["get_history_classes_api_v1_history_classes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export History */
        get: operations["export_history_api_v1_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Incidents */
        get: operations["list_incidents_api_v1_incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Incident Review */
        patch: operations["update_incident_review_api_v1_incidents__incident_id__review_patch"];
        trace?: never;
    };
    "/api/v1/streams/{camera_id}/offer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Stream Offer */
        post: operations["create_stream_offer_api_v1_streams__camera_id__offer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/streams/{camera_id}/hls.m3u8": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Hls Playlist */
        get: operations["get_hls_playlist_api_v1_streams__camera_id__hls_m3u8_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/streams/{camera_id}/hls/{resource_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Hls Resource */
        get: operations["get_hls_resource_api_v1_streams__camera_id__hls__resource_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/video_feed/{camera_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Video Feed */
        get: operations["get_video_feed_video_feed__camera_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Query */
        post: operations["resolve_query_api_v1_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BrowserDeliveryProfile */
        BrowserDeliveryProfile: {
            /**
             * Id
             * @enum {string}
             */
            id: "native" | "annotated" | "1080p15" | "720p10" | "540p5";
            /**
             * Kind
             * @enum {string}
             */
            kind: "passthrough" | "transcode";
            /** W */
            w?: number | null;
            /** H */
            h?: number | null;
            /** Fps */
            fps?: number | null;
            /** Label */
            label?: string | null;
            /** Description */
            description?: string | null;
            /** Reason */
            reason?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** BrowserDeliverySettings */
        BrowserDeliverySettings: {
            /**
             * Default Profile
             * @default 720p10
             * @enum {string}
             */
            default_profile: "native" | "annotated" | "1080p15" | "720p10" | "540p5";
            /**
             * Allow Native On Demand
             * @default true
             */
            allow_native_on_demand: boolean;
            /** Profiles */
            profiles?: {
                [key: string]: unknown;
            }[];
            /** Unsupported Profiles */
            unsupported_profiles?: {
                [key: string]: unknown;
            }[];
            native_status?: components["schemas"]["NativeAvailability"];
        };
        /** CameraCreate */
        CameraCreate: {
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
            /** Name */
            name: string;
            /** Rtsp Url */
            rtsp_url: string;
            processing_mode: components["schemas"]["ProcessingMode"];
            /**
             * Primary Model Id
             * Format: uuid
             */
            primary_model_id: string;
            /** Secondary Model Id */
            secondary_model_id?: string | null;
            tracker_type: components["schemas"]["TrackerType"];
            /** Active Classes */
            active_classes?: string[];
            runtime_vocabulary?: components["schemas"]["RuntimeVocabularyState"];
            /** Attribute Rules */
            attribute_rules?: {
                [key: string]: unknown;
            }[];
            /** Zones */
            zones?: (components["schemas"]["LineZone"] | components["schemas"]["PolygonZone"])[];
            vision_profile?: components["schemas"]["SceneVisionProfile"];
            /** Detection Regions */
            detection_regions?: components["schemas"]["DetectionRegion"][];
            homography?: components["schemas"]["HomographyPayload"] | null;
            privacy?: components["schemas"]["PrivacySettings"];
            browser_delivery?: components["schemas"]["BrowserDeliverySettings"];
            /**
             * Frame Skip
             * @default 1
             */
            frame_skip: number;
            /**
             * Fps Cap
             * @default 25
             */
            fps_cap: number;
        };
        /** CameraResponse */
        CameraResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
            /** Edge Node Id */
            edge_node_id?: string | null;
            /** Name */
            name: string;
            /** Rtsp Url Masked */
            rtsp_url_masked: string;
            processing_mode: components["schemas"]["ProcessingMode"];
            /**
             * Primary Model Id
             * Format: uuid
             */
            primary_model_id: string;
            /** Secondary Model Id */
            secondary_model_id?: string | null;
            tracker_type: components["schemas"]["TrackerType"];
            /** Active Classes */
            active_classes: string[];
            runtime_vocabulary?: components["schemas"]["RuntimeVocabularyState"];
            /** Attribute Rules */
            attribute_rules: {
                [key: string]: unknown;
            }[];
            /** Zones */
            zones: (components["schemas"]["LineZone"] | components["schemas"]["PolygonZone"] | components["schemas"]["LegacyZone"])[];
            vision_profile?: components["schemas"]["SceneVisionProfile"];
            /** Detection Regions */
            detection_regions?: components["schemas"]["DetectionRegion"][];
            homography?: components["schemas"]["HomographyPayload"] | null;
            privacy: components["schemas"]["PrivacySettings"];
            browser_delivery: components["schemas"]["BrowserDeliverySettings"];
            source_capability?: components["schemas"]["SourceCapability"] | null;
            /** Frame Skip */
            frame_skip: number;
            /** Fps Cap */
            fps_cap: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CameraSetupPreviewResponse */
        CameraSetupPreviewResponse: {
            /**
             * Camera Id
             * Format: uuid
             */
            camera_id: string;
            /** Preview Url */
            preview_url: string;
            frame_size: components["schemas"]["FrameSize"];
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
        };
        /** CameraSourceProbeRequest */
        CameraSourceProbeRequest: {
            /** Camera Id */
            camera_id?: string | null;
            /** Rtsp Url */
            rtsp_url?: string | null;
            /** @default central */
            processing_mode: components["schemas"]["ProcessingMode"];
            /** Edge Node Id */
            edge_node_id?: string | null;
            browser_delivery?: components["schemas"]["BrowserDeliverySettings"] | null;
            privacy?: components["schemas"]["PrivacySettings"] | null;
        };
        /** CameraSourceProbeResponse */
        CameraSourceProbeResponse: {
            source_capability?: components["schemas"]["SourceCapability"] | null;
            browser_delivery: components["schemas"]["BrowserDeliverySettings"];
        };
        /** CameraUpdate */
        CameraUpdate: {
            /** Site Id */
            site_id?: string | null;
            /** Name */
            name?: string | null;
            /** Rtsp Url */
            rtsp_url?: string | null;
            processing_mode?: components["schemas"]["ProcessingMode"] | null;
            /** Primary Model Id */
            primary_model_id?: string | null;
            /** Secondary Model Id */
            secondary_model_id?: string | null;
            tracker_type?: components["schemas"]["TrackerType"] | null;
            /** Active Classes */
            active_classes?: string[] | null;
            runtime_vocabulary?: components["schemas"]["RuntimeVocabularyState"] | null;
            /** Attribute Rules */
            attribute_rules?: {
                [key: string]: unknown;
            }[] | null;
            /** Zones */
            zones?: (components["schemas"]["LineZone"] | components["schemas"]["PolygonZone"])[] | null;
            vision_profile?: components["schemas"]["SceneVisionProfile"] | null;
            /** Detection Regions */
            detection_regions?: components["schemas"]["DetectionRegion"][] | null;
            homography?: components["schemas"]["HomographyPayload"] | null;
            privacy?: components["schemas"]["PrivacySettings"] | null;
            browser_delivery?: components["schemas"]["BrowserDeliverySettings"] | null;
            /** Frame Skip */
            frame_skip?: number | null;
            /** Fps Cap */
            fps_cap?: number | null;
        };
        /** CountEventBoundarySummary */
        CountEventBoundarySummary: {
            /** Boundary Id */
            boundary_id: string;
            /** Event Types */
            event_types: components["schemas"]["CountEventType"][];
        };
        /**
         * CountEventType
         * @enum {string}
         */
        CountEventType: "line_cross" | "zone_enter" | "zone_exit";
        /** DetectionRegion */
        DetectionRegion: {
            /** Id */
            id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "include" | "exclude";
            /** Polygon */
            polygon: number[][];
            /** Class Names */
            class_names?: string[];
            frame_size?: components["schemas"]["FrameSize"] | null;
            /** Points Normalized */
            points_normalized?: number[][] | null;
        };
        /**
         * DetectorCapability
         * @enum {string}
         */
        DetectorCapability: "fixed_vocab" | "open_vocab";
        /** EdgeHeartbeatRequest */
        EdgeHeartbeatRequest: {
            /**
             * Node Id
             * Format: uuid
             */
            node_id: string;
            /** Version */
            version: string;
            /** Cameras */
            cameras: number;
        };
        /** EdgeHeartbeatResponse */
        EdgeHeartbeatResponse: {
            /** Status */
            status: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
        };
        /** EdgeRegisterRequest */
        EdgeRegisterRequest: {
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
            /** Hostname */
            hostname: string;
            /** Version */
            version: string;
        };
        /** EdgeRegisterResponse */
        EdgeRegisterResponse: {
            /**
             * Edge Node Id
             * Format: uuid
             */
            edge_node_id: string;
            /** Api Key */
            api_key: string;
            /** Nats Nkey Seed */
            nats_nkey_seed: string;
            /** Subjects */
            subjects: string[];
            /** Mediamtx Url */
            mediamtx_url: string;
            /** Mediamtx Username */
            mediamtx_username?: string | null;
            /** Mediamtx Password */
            mediamtx_password?: string | null;
            /** Overlay Network Hints */
            overlay_network_hints?: {
                [key: string]: unknown;
            };
        };
        /** FleetBootstrapRequest */
        FleetBootstrapRequest: {
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
            /** Hostname */
            hostname: string;
            /** Version */
            version: string;
        };
        /** FleetBootstrapResponse */
        FleetBootstrapResponse: {
            /**
             * Edge Node Id
             * Format: uuid
             */
            edge_node_id: string;
            /** Api Key */
            api_key: string;
            /** Nats Nkey Seed */
            nats_nkey_seed: string;
            /** Subjects */
            subjects: string[];
            /** Mediamtx Url */
            mediamtx_url: string;
            /** Mediamtx Username */
            mediamtx_username?: string | null;
            /** Mediamtx Password */
            mediamtx_password?: string | null;
            /** Overlay Network Hints */
            overlay_network_hints?: {
                [key: string]: unknown;
            };
            /** Dev Compose Command */
            dev_compose_command: string;
            /** Supervisor Environment */
            supervisor_environment?: {
                [key: string]: string;
            };
        };
        /** FleetCameraWorkerSummary */
        FleetCameraWorkerSummary: {
            /**
             * Camera Id
             * Format: uuid
             */
            camera_id: string;
            /** Camera Name */
            camera_name: string;
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
            /** Node Id */
            node_id?: string | null;
            /** Node Hostname */
            node_hostname?: string | null;
            processing_mode: components["schemas"]["ProcessingMode"];
            desired_state: components["schemas"]["WorkerDesiredState"];
            runtime_status: components["schemas"]["WorkerRuntimeStatus"];
            /**
             * Lifecycle Owner
             * @enum {string}
             */
            lifecycle_owner: "manual_dev" | "central_supervisor" | "edge_supervisor" | "none";
            /** Dev Run Command */
            dev_run_command?: string | null;
            /** Detail */
            detail?: string | null;
        };
        /** FleetDeliveryDiagnostic */
        FleetDeliveryDiagnostic: {
            /**
             * Camera Id
             * Format: uuid
             */
            camera_id: string;
            /** Camera Name */
            camera_name: string;
            processing_mode: components["schemas"]["ProcessingMode"];
            /** Assigned Node Id */
            assigned_node_id?: string | null;
            source_capability?: components["schemas"]["SourceCapability"] | null;
            /**
             * Default Profile
             * @enum {string}
             */
            default_profile: "native" | "annotated" | "1080p15" | "720p10" | "540p5";
            /** Available Profiles */
            available_profiles?: components["schemas"]["BrowserDeliveryProfile"][];
            native_status?: components["schemas"]["NativeAvailability"];
            /**
             * Selected Stream Mode
             * @enum {string}
             */
            selected_stream_mode: "passthrough" | "transcode";
        };
        /**
         * FleetLifecycleMode
         * @enum {string}
         */
        FleetLifecycleMode: "manual_dev" | "supervised" | "mixed";
        /**
         * FleetNodeStatus
         * @enum {string}
         */
        FleetNodeStatus: "healthy" | "stale" | "offline" | "unknown";
        /** FleetNodeSummary */
        FleetNodeSummary: {
            /** Id */
            id?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "central" | "edge";
            /** Hostname */
            hostname: string;
            /** Site Id */
            site_id?: string | null;
            status: components["schemas"]["FleetNodeStatus"];
            /** Version */
            version?: string | null;
            /** Last Seen At */
            last_seen_at?: string | null;
            /** Assigned Camera Ids */
            assigned_camera_ids?: string[];
            /** Reported Camera Count */
            reported_camera_count?: number | null;
        };
        /** FleetOverviewResponse */
        FleetOverviewResponse: {
            mode: components["schemas"]["FleetLifecycleMode"];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            summary: components["schemas"]["FleetSummary"];
            /** Nodes */
            nodes: components["schemas"]["FleetNodeSummary"][];
            /** Camera Workers */
            camera_workers: components["schemas"]["FleetCameraWorkerSummary"][];
            /** Delivery Diagnostics */
            delivery_diagnostics: components["schemas"]["FleetDeliveryDiagnostic"][];
        };
        /** FleetSummary */
        FleetSummary: {
            /** Desired Workers */
            desired_workers: number;
            /** Running Workers */
            running_workers: number;
            /** Stale Nodes */
            stale_nodes: number;
            /** Offline Nodes */
            offline_nodes: number;
            /** Native Unavailable Cameras */
            native_unavailable_cameras: number;
        };
        /** FrameSize */
        FrameSize: {
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryBucketCoverage */
        HistoryBucketCoverage: {
            /**
             * Bucket
             * Format: date-time
             */
            bucket: string;
            status: components["schemas"]["HistoryCoverageStatus"];
            /** Reason */
            reason?: string | null;
        };
        /** HistoryClassEntry */
        HistoryClassEntry: {
            /** Class Name */
            class_name: string;
            /** Event Count */
            event_count: number;
            /** Has Speed Data */
            has_speed_data: boolean;
        };
        /** HistoryClassesResponse */
        HistoryClassesResponse: {
            /**
             * From
             * Format: date-time
             */
            from: string;
            /**
             * To
             * Format: date-time
             */
            to: string;
            metric?: components["schemas"]["HistoryMetric"] | null;
            /** Boundaries */
            boundaries?: components["schemas"]["CountEventBoundarySummary"][];
            /** Classes */
            classes: components["schemas"]["HistoryClassEntry"][];
        };
        /**
         * HistoryCoverageStatus
         * @enum {string}
         */
        HistoryCoverageStatus: "populated" | "zero" | "no_telemetry" | "camera_offline" | "worker_offline" | "source_unavailable" | "no_scope" | "access_limited";
        /**
         * HistoryMetric
         * @enum {string}
         */
        HistoryMetric: "occupancy" | "count_events" | "observations";
        /** HistoryPoint */
        HistoryPoint: {
            /**
             * Bucket
             * Format: date-time
             */
            bucket: string;
            /** Camera Id */
            camera_id?: string | null;
            /** Class Name */
            class_name: string;
            /** Event Count */
            event_count: number;
            /** Granularity */
            granularity: string;
            metric?: components["schemas"]["HistoryMetric"] | null;
        };
        /** HistorySeriesResponse */
        HistorySeriesResponse: {
            /** Granularity */
            granularity: string;
            metric?: components["schemas"]["HistoryMetric"] | null;
            /** Class Names */
            class_names: string[];
            /** Rows */
            rows: components["schemas"]["HistorySeriesRow"][];
            /**
             * Granularity Adjusted
             * @default false
             */
            granularity_adjusted: boolean;
            /**
             * Speed Classes Capped
             * @default false
             */
            speed_classes_capped: boolean;
            /** Speed Classes Used */
            speed_classes_used?: string[] | null;
            /** Effective From */
            effective_from?: string | null;
            /** Effective To */
            effective_to?: string | null;
            /**
             * Bucket Count
             * @default 0
             */
            bucket_count: number;
            /** Bucket Span */
            bucket_span?: string | null;
            /** @default populated */
            coverage_status: components["schemas"]["HistoryCoverageStatus"];
            /** Coverage By Bucket */
            coverage_by_bucket?: components["schemas"]["HistoryBucketCoverage"][];
        };
        /** HistorySeriesRow */
        HistorySeriesRow: {
            /**
             * Bucket
             * Format: date-time
             */
            bucket: string;
            /** Values */
            values: {
                [key: string]: number;
            };
            /** Total Count */
            total_count: number;
            /** Speed P50 */
            speed_p50?: {
                [key: string]: number;
            } | null;
            /** Speed P95 */
            speed_p95?: {
                [key: string]: number;
            } | null;
            /** Speed Sample Count */
            speed_sample_count?: {
                [key: string]: number;
            } | null;
            /** Over Threshold Count */
            over_threshold_count?: {
                [key: string]: number;
            } | null;
        };
        /** HomographyPayload */
        HomographyPayload: {
            /** Src */
            src: number[][];
            /** Dst */
            dst: number[][];
            /** Ref Distance M */
            ref_distance_m: number;
        };
        /** IncidentResponse */
        IncidentResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Camera Id
             * Format: uuid
             */
            camera_id: string;
            /** Camera Name */
            camera_name?: string | null;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Type */
            type: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Snapshot Url */
            snapshot_url?: string | null;
            /** Clip Url */
            clip_url?: string | null;
            /**
             * Storage Bytes
             * @default 0
             */
            storage_bytes: number;
            /** @default pending */
            review_status: components["schemas"]["IncidentReviewStatus"];
            /** Reviewed At */
            reviewed_at?: string | null;
            /** Reviewed By Subject */
            reviewed_by_subject?: string | null;
        };
        /**
         * IncidentReviewStatus
         * @enum {string}
         */
        IncidentReviewStatus: "pending" | "reviewed";
        /** IncidentReviewUpdate */
        IncidentReviewUpdate: {
            review_status: components["schemas"]["IncidentReviewStatus"];
        };
        /** LegacyZone */
        LegacyZone: {
            /** Id */
            id?: string | null;
            /** Class Names */
            class_names?: string[] | null;
            frame_size?: components["schemas"]["FrameSize"] | null;
            /** Points Normalized */
            points_normalized?: number[][] | null;
            /** Type */
            type?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** LineZone */
        LineZone: {
            /** Id */
            id?: string | null;
            /** Class Names */
            class_names?: string[] | null;
            frame_size?: components["schemas"]["FrameSize"] | null;
            /** Points Normalized */
            points_normalized?: number[][] | null;
            /**
             * Type
             * @constant
             */
            type: "line";
            /** Points */
            points: number[][];
        } & {
            [key: string]: unknown;
        };
        /** ModelCapabilityConfig */
        ModelCapabilityConfig: {
            /**
             * Supports Runtime Vocabulary Updates
             * @default false
             */
            supports_runtime_vocabulary_updates: boolean;
            /** Max Runtime Terms */
            max_runtime_terms?: number | null;
            /** Prompt Format */
            prompt_format?: ("labels" | "phrases") | null;
            /** Execution Profiles */
            execution_profiles?: string[];
            /** Model Family */
            model_family?: ("yolo11" | "yolo12" | "yolo26" | "yolo_world" | "yoloe") | null;
            /** Runtime Backend */
            runtime_backend?: ("onnxruntime" | "ultralytics_yolo_world" | "ultralytics_yoloe" | "tensorrt_engine") | null;
            /** Readiness */
            readiness?: ("ready" | "experimental" | "planned") | null;
            /** Recommended Profiles */
            recommended_profiles?: string[];
            /**
             * Requires Gpu
             * @default false
             */
            requires_gpu: boolean;
            /**
             * Supports Masks
             * @default false
             */
            supports_masks: boolean;
            /** Source Url */
            source_url?: string | null;
        };
        /** ModelCatalogEntryResponse */
        ModelCatalogEntryResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
            task: components["schemas"]["ModelTask"];
            /** Path Hint */
            path_hint: string;
            format: components["schemas"]["ModelFormat"];
            capability: components["schemas"]["DetectorCapability"];
            capability_config: components["schemas"]["ModelCapabilityConfig"];
            /** Classes */
            classes?: string[];
            /** Input Shape */
            input_shape: {
                [key: string]: number;
            };
            /** Sha256 */
            sha256?: string | null;
            /** Size Bytes */
            size_bytes?: number | null;
            /** License */
            license?: string | null;
            registration_state: components["schemas"]["ModelCatalogRegistrationState"];
            /** Registered Model Id */
            registered_model_id?: string | null;
            /**
             * Artifact Exists
             * @default false
             */
            artifact_exists: boolean;
            /** Note */
            note: string;
        };
        /**
         * ModelCatalogRegistrationState
         * @enum {string}
         */
        ModelCatalogRegistrationState: "unregistered" | "registered" | "missing_artifact" | "planned";
        /** ModelCreate */
        ModelCreate: {
            /** Name */
            name: string;
            /** Version */
            version: string;
            task: components["schemas"]["ModelTask"];
            /** Path */
            path: string;
            format: components["schemas"]["ModelFormat"];
            /** @default fixed_vocab */
            capability: components["schemas"]["DetectorCapability"];
            capability_config?: components["schemas"]["ModelCapabilityConfig"];
            /** Classes */
            classes?: string[] | null;
            /** Input Shape */
            input_shape: {
                [key: string]: number;
            };
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** License */
            license?: string | null;
        };
        /**
         * ModelFormat
         * @enum {string}
         */
        ModelFormat: "onnx" | "engine" | "pt";
        /** ModelResponse */
        ModelResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
            task: components["schemas"]["ModelTask"];
            /** Path */
            path: string;
            format: components["schemas"]["ModelFormat"];
            /** @default fixed_vocab */
            capability: components["schemas"]["DetectorCapability"];
            capability_config?: components["schemas"]["ModelCapabilityConfig"];
            /** Classes */
            classes: string[];
            /** Input Shape */
            input_shape: {
                [key: string]: number;
            };
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** License */
            license?: string | null;
        };
        /**
         * ModelTask
         * @enum {string}
         */
        ModelTask: "detect" | "classify" | "attribute";
        /** ModelUpdate */
        ModelUpdate: {
            /** Name */
            name?: string | null;
            /** Version */
            version?: string | null;
            task?: components["schemas"]["ModelTask"] | null;
            /** Path */
            path?: string | null;
            format?: components["schemas"]["ModelFormat"] | null;
            capability?: components["schemas"]["DetectorCapability"] | null;
            capability_config?: components["schemas"]["ModelCapabilityConfig"] | null;
            /** Classes */
            classes?: string[] | null;
            /** Input Shape */
            input_shape?: {
                [key: string]: number;
            } | null;
            /** Sha256 */
            sha256?: string | null;
            /** Size Bytes */
            size_bytes?: number | null;
            /** License */
            license?: string | null;
        };
        /** MotionMetricsSettings */
        MotionMetricsSettings: {
            /**
             * Speed Enabled
             * @default false
             */
            speed_enabled: boolean;
        };
        /** NativeAvailability */
        NativeAvailability: {
            /**
             * Available
             * @default true
             */
            available: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** PolygonZone */
        PolygonZone: {
            /** Id */
            id?: string | null;
            /** Class Names */
            class_names?: string[] | null;
            frame_size?: components["schemas"]["FrameSize"] | null;
            /** Points Normalized */
            points_normalized?: number[][] | null;
            /** Type */
            type?: "polygon" | null;
            /** Polygon */
            polygon: number[][];
        } & {
            [key: string]: unknown;
        };
        /** PrivacySettings */
        PrivacySettings: {
            /**
             * Blur Faces
             * @default true
             */
            blur_faces: boolean;
            /**
             * Blur Plates
             * @default true
             */
            blur_plates: boolean;
            /**
             * Method
             * @default gaussian
             * @enum {string}
             */
            method: "gaussian" | "pixelate";
            /**
             * Strength
             * @default 7
             */
            strength: number;
        };
        /**
         * ProcessingMode
         * @enum {string}
         */
        ProcessingMode: "central" | "edge" | "hybrid";
        /**
         * PublishProfile
         * @enum {string}
         */
        PublishProfile: "jetson-nano" | "central-gpu";
        /** QueryRequest */
        QueryRequest: {
            /** Prompt */
            prompt: string;
            /** Camera Ids */
            camera_ids: string[];
        };
        /**
         * QueryResolutionMode
         * @enum {string}
         */
        QueryResolutionMode: "fixed_filter" | "open_vocab";
        /** QueryResponse */
        QueryResponse: {
            /** @default fixed_filter */
            resolution_mode: components["schemas"]["QueryResolutionMode"];
            /** Resolved Classes */
            resolved_classes: string[];
            /** Resolved Vocabulary */
            resolved_vocabulary?: string[];
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Latency Ms */
            latency_ms: number;
            /** Camera Ids */
            camera_ids: string[];
        };
        /**
         * RuntimeVocabularySource
         * @enum {string}
         */
        RuntimeVocabularySource: "default" | "query" | "manual";
        /** RuntimeVocabularyState */
        RuntimeVocabularyState: {
            /** Terms */
            terms?: string[];
            /** @default default */
            source: components["schemas"]["RuntimeVocabularySource"];
            /**
             * Version
             * @default 0
             */
            version: number;
            /** Updated At */
            updated_at?: string | null;
        };
        /** SceneVisionProfile */
        SceneVisionProfile: {
            /**
             * Compute Tier
             * @default edge_standard
             * @enum {string}
             */
            compute_tier: "cpu_low" | "edge_standard" | "edge_advanced_jetson" | "central_gpu";
            /**
             * Accuracy Mode
             * @default balanced
             * @enum {string}
             */
            accuracy_mode: "fast" | "balanced" | "maximum_accuracy" | "open_vocabulary";
            /**
             * Scene Difficulty
             * @default cluttered
             * @enum {string}
             */
            scene_difficulty: "open" | "cluttered" | "occluded" | "crowded" | "traffic" | "custom";
            /**
             * Object Domain
             * @default mixed
             * @enum {string}
             */
            object_domain: "people" | "vehicles" | "mixed" | "open_vocab";
            motion_metrics?: components["schemas"]["MotionMetricsSettings"];
            /** Candidate Quality */
            candidate_quality?: {
                [key: string]: unknown;
            };
            /** Tracker Profile */
            tracker_profile?: {
                [key: string]: unknown;
            };
            /** Verifier Profile */
            verifier_profile?: {
                [key: string]: unknown;
            };
        };
        /** SiteCreate */
        SiteCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Tz
             * @default UTC
             */
            tz: string;
            /** Geo Point */
            geo_point?: {
                [key: string]: number;
            } | null;
        };
        /** SiteResponse */
        SiteResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Tz */
            tz: string;
            /** Geo Point */
            geo_point?: {
                [key: string]: number;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SiteUpdate */
        SiteUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Tz */
            tz?: string | null;
            /** Geo Point */
            geo_point?: {
                [key: string]: number;
            } | null;
        };
        /** SourceCapability */
        SourceCapability: {
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Fps */
            fps?: number | null;
            /** Codec */
            codec?: string | null;
            /** Aspect Ratio */
            aspect_ratio?: string | null;
        };
        /**
         * StreamMode
         * @enum {string}
         */
        StreamMode: "passthrough" | "filtered-preview" | "annotated-whip";
        /** StreamOfferRequest */
        StreamOfferRequest: {
            /** Sdp Offer */
            sdp_offer: string;
        };
        /** StreamOfferResponse */
        StreamOfferResponse: {
            /**
             * Camera Id
             * Format: uuid
             */
            camera_id: string;
            /** Sdp Answer */
            sdp_answer: string;
        };
        /** TelemetryEnvelope */
        TelemetryEnvelope: {
            /** Events */
            events?: components["schemas"]["TelemetryFrame"][];
        };
        /** TelemetryFrame */
        TelemetryFrame: {
            /**
             * Camera Id
             * Format: uuid
             */
            camera_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            profile: components["schemas"]["PublishProfile"];
            stream_mode: components["schemas"]["StreamMode"];
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Tracks */
            tracks: components["schemas"]["TelemetryTrack"][];
        };
        /** TelemetryTrack */
        TelemetryTrack: {
            /** Class Name */
            class_name: string;
            /** Confidence */
            confidence: number;
            /** Bbox */
            bbox: {
                [key: string]: number;
            };
            /** Track Id */
            track_id: number;
            /** Stable Track Id */
            stable_track_id?: number | null;
            /** Track State */
            track_state?: ("active" | "coasting") | null;
            /** Last Seen Age Ms */
            last_seen_age_ms?: number | null;
            /** Source Track Id */
            source_track_id?: number | null;
            /** Speed Kph */
            speed_kph?: number | null;
            /** Direction Deg */
            direction_deg?: number | null;
            /** Zone Id */
            zone_id?: string | null;
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            };
        };
        /**
         * TrackerType
         * @enum {string}
         */
        TrackerType: "botsort" | "bytetrack" | "ocsort";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkerCameraSettings */
        WorkerCameraSettings: {
            /** Rtsp Url */
            rtsp_url: string;
            /**
             * Frame Skip
             * @default 1
             */
            frame_skip: number;
            /**
             * Fps Cap
             * @default 25
             */
            fps_cap: number;
        };
        /** WorkerConfigResponse */
        WorkerConfigResponse: {
            /**
             * Camera Id
             * Format: uuid
             */
            camera_id: string;
            mode: components["schemas"]["ProcessingMode"];
            camera: components["schemas"]["WorkerCameraSettings"];
            publish?: components["schemas"]["WorkerPublishSettings"];
            stream?: components["schemas"]["WorkerStreamSettings"];
            model: components["schemas"]["WorkerModelSettings"];
            secondary_model?: components["schemas"]["WorkerModelSettings"] | null;
            tracker: components["schemas"]["WorkerTrackerSettings"];
            privacy?: components["schemas"]["WorkerPrivacySettings"];
            /** Active Classes */
            active_classes?: string[];
            runtime_vocabulary?: components["schemas"]["RuntimeVocabularyState"];
            runtime_capability?: components["schemas"]["WorkerRuntimeCapability"];
            /** Attribute Rules */
            attribute_rules?: {
                [key: string]: unknown;
            }[];
            /** Zones */
            zones?: (components["schemas"]["WorkerLineZone"] | components["schemas"]["WorkerPolygonZone"] | components["schemas"]["LegacyZone"])[];
            vision_profile?: components["schemas"]["SceneVisionProfile"];
            /** Detection Regions */
            detection_regions?: components["schemas"]["DetectionRegion"][];
            /** Homography */
            homography?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * WorkerDesiredState
         * @enum {string}
         */
        WorkerDesiredState: "desired" | "not_desired" | "manual" | "supervised";
        /** WorkerLineZone */
        WorkerLineZone: {
            /** Id */
            id?: string | null;
            /** Class Names */
            class_names?: string[] | null;
            /**
             * Type
             * @constant
             */
            type: "line";
            /** Points */
            points: number[][];
        } & {
            [key: string]: unknown;
        };
        /** WorkerModelSettings */
        WorkerModelSettings: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** @default fixed_vocab */
            capability: components["schemas"]["DetectorCapability"];
            capability_config?: components["schemas"]["ModelCapabilityConfig"];
            /** Classes */
            classes: string[];
            /** Input Shape */
            input_shape: {
                [key: string]: number;
            };
            runtime_vocabulary?: components["schemas"]["RuntimeVocabularyState"];
            /**
             * Confidence Threshold
             * @default 0.25
             */
            confidence_threshold: number;
            /**
             * Iou Threshold
             * @default 0.45
             */
            iou_threshold: number;
        };
        /** WorkerPolygonZone */
        WorkerPolygonZone: {
            /** Id */
            id?: string | null;
            /** Class Names */
            class_names?: string[] | null;
            /** Type */
            type?: "polygon" | null;
            /** Polygon */
            polygon: number[][];
        } & {
            [key: string]: unknown;
        };
        /** WorkerPrivacySettings */
        WorkerPrivacySettings: {
            /**
             * Blur Faces
             * @default true
             */
            blur_faces: boolean;
            /**
             * Blur Plates
             * @default true
             */
            blur_plates: boolean;
            /**
             * Method
             * @default gaussian
             * @enum {string}
             */
            method: "gaussian" | "pixelate";
            /**
             * Strength
             * @default 7
             */
            strength: number;
        };
        /** WorkerPublishSettings */
        WorkerPublishSettings: {
            /**
             * Subject Prefix
             * @default evt.tracking
             */
            subject_prefix: string;
            /** Http Fallback Url */
            http_fallback_url?: string | null;
        };
        /** WorkerRuntimeCapability */
        WorkerRuntimeCapability: {
            /** Execution Profiles */
            execution_profiles?: string[];
            /** Detector Capabilities */
            detector_capabilities?: components["schemas"]["DetectorCapability"][];
            /**
             * Hot Runtime Vocabulary Updates
             * @default false
             */
            hot_runtime_vocabulary_updates: boolean;
            /** Max Runtime Terms */
            max_runtime_terms?: number | null;
        };
        /**
         * WorkerRuntimeStatus
         * @enum {string}
         */
        WorkerRuntimeStatus: "running" | "stale" | "offline" | "unknown" | "not_reported";
        /** WorkerStreamSettings */
        WorkerStreamSettings: {
            /**
             * Profile Id
             * @default native
             * @enum {string}
             */
            profile_id: "native" | "annotated" | "1080p15" | "720p10" | "540p5";
            /**
             * Kind
             * @default passthrough
             * @enum {string}
             */
            kind: "passthrough" | "transcode";
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
            /**
             * Fps
             * @default 25
             */
            fps: number;
        };
        /** WorkerTrackerSettings */
        WorkerTrackerSettings: {
            tracker_type: components["schemas"]["TrackerType"];
            /**
             * Frame Rate
             * @default 25
             */
            frame_rate: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthcheck_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    debug_protected_api_v1_debug_protected_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    edge_ping_api_v1_edge_ping_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_sites_api_v1_sites_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_site_api_v1_sites_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_site_api_v1_sites__site_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_site_api_v1_sites__site_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_site_api_v1_sites__site_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cameras_api_v1_cameras_get: {
        parameters: {
            query?: {
                site_id?: string | null;
            };
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_camera_api_v1_cameras_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CameraCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    probe_camera_source_api_v1_cameras_source_probe_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CameraSourceProbeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraSourceProbeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_camera_api_v1_cameras__camera_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_camera_api_v1_cameras__camera_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_camera_api_v1_cameras__camera_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CameraUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_camera_worker_config_api_v1_cameras__camera_id__worker_config_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_camera_setup_preview_api_v1_cameras__camera_id__setup_preview_get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraSetupPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_camera_setup_preview_image_api_v1_cameras__camera_id__setup_preview_image_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelResponse"][];
                };
            };
        };
    };
    create_model_api_v1_models_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_model_api_v1_models__model_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_model_catalog_api_v1_model_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelCatalogEntryResponse"][];
                };
            };
        };
    };
    register_edge_node_api_v1_edge_register_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EdgeRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeRegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_edge_telemetry_api_v1_edge_telemetry_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelemetryEnvelope"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edge_heartbeat_api_v1_edge_heartbeat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EdgeHeartbeatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeHeartbeatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fleet_overview_api_v1_operations_fleet_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FleetOverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_bootstrap_material_api_v1_operations_bootstrap_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FleetBootstrapRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FleetBootstrapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_api_v1_history_get: {
        parameters: {
            query: {
                from: string;
                to: string;
                camera_id?: string | null;
                camera_ids?: string[] | null;
                class_names?: string[] | null;
                granularity?: string;
                metric?: components["schemas"]["HistoryMetric"];
            };
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_series_api_v1_history_series_get: {
        parameters: {
            query: {
                from: string;
                to: string;
                camera_id?: string | null;
                camera_ids?: string[] | null;
                class_names?: string[] | null;
                granularity?: string;
                metric?: components["schemas"]["HistoryMetric"];
                include_speed?: boolean;
                speed_threshold?: number | null;
            };
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistorySeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_classes_api_v1_history_classes_get: {
        parameters: {
            query: {
                from: string;
                to: string;
                camera_id?: string | null;
                camera_ids?: string[] | null;
                metric?: components["schemas"]["HistoryMetric"];
            };
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryClassesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_history_api_v1_export_get: {
        parameters: {
            query: {
                from: string;
                to: string;
                camera_id?: string | null;
                camera_ids?: string[] | null;
                class_names?: string[] | null;
                granularity?: string;
                format?: string;
                metric?: components["schemas"]["HistoryMetric"];
            };
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_incidents_api_v1_incidents_get: {
        parameters: {
            query?: {
                camera_id?: string | null;
                type?: string | null;
                review_status?: components["schemas"]["IncidentReviewStatus"] | null;
                limit?: number;
            };
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_incident_review_api_v1_incidents__incident_id__review_patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncidentReviewUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_stream_offer_api_v1_streams__camera_id__offer_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StreamOfferRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamOfferResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hls_playlist_api_v1_streams__camera_id__hls_m3u8_get: {
        parameters: {
            query?: {
                tenant_id?: string | null;
            };
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hls_resource_api_v1_streams__camera_id__hls__resource_path__get: {
        parameters: {
            query?: {
                tenant_id?: string | null;
            };
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path: {
                camera_id: string;
                resource_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_video_feed_video_feed__camera_id__get: {
        parameters: {
            query?: {
                tenant_id?: string | null;
            };
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_query_api_v1_query_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
